name = "r2-ai-workflow"
main = "src/index.ts"
compatibility_date = "2025-06-17"

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "upload-and-summarize-workflow"
binding = "UPLOAD_AND_SUMMARIZE_WORKFLOW"
class_name = "UploadAndSummarizeW"

[[workflows]]
name = "github-queue-fetchreadme-upload-summarize-workflow"
binding = "GITHUB_QUEUE_FETCHREADME_UPLOAD_SUMMARIZE_WORKFLOW"
class_name = "GitHubQueueFetchreadmeUploadSummarizeW"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "github-readme-full"
preview_bucket_name = "github-readme-full-dev"

[[r2_buckets]]
binding = "R2_BUCKET_SUMMARY"
bucket_name = "github-readme-summary"
preview_bucket_name = "github-readme-summary-dev"

[[queues.producers]]
binding = "GITHUB_QUEUE"
queue = "queue-github-parsing"
